version: '3.8'
services:
    cache:
        image: redis
        restart: always
        ports:
            - '6380:6379'
        volumes:
            - cache:/data
volumes:
    cache:
        driver: local
